export {
  DEFAULT_SCALE,
  DEFAULT_THEME,
  KEYS,
  MAX_DISPLAYED_SUGGESTIONS,
  SCALES,
  SUPPORTED_SEARCH_SUGGESTIONS,
  THEMES,
  EMPTY_STRING,
  SUGGESTIONS_ENDPOINT,
  SUGGESTIONS_URL,
  DATA_ENDPOINT,
  DATA_URL,
  SEARCH_QUERY_PARAM,
} from "./main"
export type { Global } from "./types"
